sudo: required
language: node_js

services:
  - docker

branches:
  only:
  - master

install: true
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t kabbageinc/kalemail:latest .
after_success: docker push kabbageinc/kalemail:latest
after_script: docker rmi -f kabbageinc/kalemail:latest
